"""Derive a tool's ADVERTISED parameter shape from the SDK request DTO.

The problem this removes
------------------------
An MCP tool's advertised ``inputSchema`` is generated by FastMCP from the Python
signature -- there is no separate declaration and no override hook. So the shape buyers
see has always been hand-written, and nothing tied it to the request DTO the SDK ships.
The two drifted freely: ``get_adcp_capabilities`` advertised ``protocols: list[str]``
where the DTO declares a typed enum, and ``ext: dict`` where the DTO declares
``ExtensionObject``. A buyer reading our schema and a buyer reading the spec saw
different contracts, and nothing failed.

The rule
--------
**Announced = the parameters the tool actually accepts; the DTO supplies the type of
every field it declares.** Both halves matter:

* A DTO field the tool does NOT accept is NOT announced. We never advertise a parameter
  the implementation would ignore, and there is no hand-maintained list of "unimplemented"
  fields to fall out of date -- absence from the signature IS the statement. To expose a
  new spec field you make the tool accept it, and the announcement follows automatically.
* A parameter the DTO DOES declare takes the DTO's type. This is the half that cannot
  drift: bump the SDK and every advertised type moves with it.

A parameter the DTO does not declare is DROPPED from the announcement -- that is what
retires a legacy flat name such as ``list_creatives(status=...)``: FastMCP never passes what
it does not advertise, so there is no list of retired names to maintain. (This paragraph
used to say such a parameter "is still announced"; it never did, and a reader debugging why
a flat name stopped working was sent the wrong way by it.) Our advertised shape is therefore
always a SUBSET of the DTO, in exactly the DTO's form.

Transport independence
----------------------
This governs the ADVERTISED shape, which only MCP publishes. It deliberately does not
touch behaviour: A2A and REST reach the same ``_impl`` through the same request seam, so
the accepted field set and its meaning are identical everywhere and only the envelope
differs. Nothing here may become a per-transport branch.
"""

from __future__ import annotations

import inspect
import re
import sys
import typing
from collections.abc import Callable
from typing import Annotated, Any

from pydantic import BaseModel
from pydantic import Field as PydanticField


def _is_injected(parameter: inspect.Parameter) -> bool:
    """True for a parameter FastMCP injects rather than one a buyer sends.

    Detected by ANNOTATION, not by a list of names. The only such parameter is the FastMCP
    ``Context``: it must stay in the signature so FastMCP can inject it, and FastMCP already
    keeps it out of the advertised schema. Everything else must be a DTO field or it is not
    a request parameter at all -- there is no denylist to maintain, because "is this buyer
    data?" is answered by the DTO, not by a name.
    """
    annotation = parameter.annotation
    if annotation is inspect.Parameter.empty:
        return False
    # Match the TYPE, not the spelling. A substring test on "Context" also matches the
    # spec's own ``ContextObject`` -- a real request field -- and would silently stop
    # advertising it.
    from fastmcp.server.context import Context as _FastMCPContext

    if any(arg is _FastMCPContext for arg in (annotation, *typing.get_args(annotation))):
        return True
    # Under `from __future__ import annotations` the annotation arrives as a STRING, so
    # get_args() returns () and the type test above sees nothing. Modules differ on this,
    # so the check must handle both: get_media_buys.ctx is 'Context | ToolContext | None'
    # while get_adcp_capabilities.ctx is the resolved class. Missing the string form drops
    # ctx from the derived signature, FastMCP then has nothing to inject, and every call
    # arrives without identity -- AUTH_MISSING on a properly authenticated request.
    if isinstance(annotation, str):
        return bool(re.search(r"\bContext\b", annotation))
    return False


#: Names a builder. The tool -> DTO edge is read from the ARTIFACT -- the builder the
#: wrapper actually references in its BYTECODE, and that builder's return annotation --
#: never from the tool's NAME. Name-joining would be fooled by the real cases:
#: ``_build_update_request`` returns ``UpdateMediaBuyRequest``. Reading ``co_names``
#: rather than source text also keeps this out of reach of the source-scanning ban
#: (a bytecode reference is the call itself, not a string that resembles one).
_BUILDER_NAME = re.compile(r"^(_?build_\w+_request|create_\w+_request)$")


def builder_for(fn: Callable[..., Any]) -> Callable[..., Any] | None:
    """The ONE builder a tool constructs its request through, or None when it has none.

    This is the tool -> builder edge, and every transport reads it rather than re-deriving
    "params to request" for itself. That is the whole point: a transport that looks the
    builder up cannot pick a different spelling, because there is nothing to pick.

    Resolved from the ARTIFACT -- the builder named in the wrapper's BYTECODE -- never from
    the tool's name. Name-joining would be fooled by the real cases: ``_build_update_request``
    returns ``UpdateMediaBuyRequest``.
    """
    builder_name = next((n for n in fn.__code__.co_names if _BUILDER_NAME.match(n)), None)
    if builder_name is None:
        return None

    module = sys.modules.get(fn.__module__)
    builder = getattr(module, builder_name, None)
    if builder is None:
        # Builders are often imported inside the function body; find the one module that
        # defines this name among those already imported.
        for loaded in list(sys.modules.values()):
            candidate = getattr(loaded, builder_name, None)
            if candidate is not None and getattr(candidate, "__name__", None) == builder_name:
                builder = candidate
                break
    return builder


def request_model_for(fn: Callable[..., Any]) -> type[BaseModel] | None:
    """The request DTO a tool builds, or None when it builds none.

    Derived from ``builder_for`` so the DTO and the builder can never disagree about which
    seam a tool uses -- they are the same lookup, read once.
    """
    builder = builder_for(fn)
    if builder is None:
        return None
    try:
        hints = typing.get_type_hints(builder)
    except Exception:
        return None
    model = hints.get("return")
    return model if isinstance(model, type) and issubclass(model, BaseModel) else None


def _declared_description(annotation: Any) -> str | None:
    """The description already on the tool's own ``Annotated[...]``, if any.

    Taking the DTO's type must not silently erase buyer-facing text the tool wrote. A DTO
    field with no description of its own would otherwise blank the wrapper's -- five
    parameters lost their description that way before this existed, invisibly, because the
    advertised schema still validated.
    """
    if typing.get_origin(annotation) is not Annotated:
        return None
    for meta in typing.get_args(annotation)[1:]:
        description = getattr(meta, "description", None)
        if description:
            return str(description)
    return None


def derived_signature(fn: Callable[..., Any], model: type[BaseModel]) -> inspect.Signature:
    """``fn``'s own parameters, retyped from ``model`` wherever it declares the field.

    The advertised type is the DTO's, always. Where this agent accepts MORE than the library
    (the brand shorthand), the widening is declared ON THE MODEL, so advertised == accepted
    without the derivation needing a narrowing rule. An earlier version guarded the narrow
    direction here instead; that put the exception in the wrong place and the model went on
    claiming a shape the tool did not implement.
    """
    signature = inspect.signature(fn)
    parameters = []
    for name, parameter in signature.parameters.items():
        if _is_injected(parameter):
            parameters.append(parameter)
            continue
        field = model.model_fields.get(name)
        if field is None:
            # Declared by the tool but NOT by the DTO -- a non-spec parameter. Dropped from
            # the advertised shape, which is what retires it: FastMCP never passes what it
            # does not advertise. No allowlist of legacy names to maintain; absence from
            # the DTO is the whole statement.
            continue
        declared = parameter.annotation
        description = field.description or _declared_description(declared)
        # Typed Any because the two arms are genuinely different kinds: `field.annotation`
        # is a runtime type, while `Annotated[...]` is a typing special form. mypy inferred
        # the variable from the first assignment and then rejected the second; the value is
        # handed straight to Parameter.replace, which takes either.
        annotation: Any = field.annotation
        if description:
            annotation = Annotated[annotation, PydanticField(description=description)]
        parameters.append(parameter.replace(annotation=annotation))
    return signature.replace(parameters=parameters)


def apply_dto_announced_shape(target: Callable[..., Any], source_fn: Callable[..., Any]) -> bool:
    """Point ``target``'s advertised signature at the DTO. True when one was applied.

    ``target`` is what gets registered (the error-logging wrapper); ``source_fn`` is the
    undecorated tool, whose body names the builder.

    The model is resolved from the builder, full stop. The ``dto`` override this used to
    accept is gone with its last caller (list_tasks, rebased onto the SDK vocabulary): an
    unused override is one refactor away from being used again, and its whole effect was to
    let a tool advertise a shape no builder constructs.
    """
    model = request_model_for(source_fn)
    if model is None:
        return False
    signature = derived_signature(source_fn, model)

    # A REQUIRED DTO field the wrapper does not declare can never be populated: the builder
    # never receives it, so every call raises ValidationError. That is a loud failure, but it
    # arrives at CALL time, on a buyer's request, for a defect fixed in one line at author
    # time. Measured across all 16 tools when this was added, no tool was in that state --
    # which is exactly when to nail it down, since the refusal costs nothing today and the
    # next tool cannot introduce it.
    #
    # Refusing rather than allowlisting, for the same reason _register_tool refuses an
    # unresolvable DTO: a list of known-broken tools records the violation, whereas refusing
    # makes the broken state unreachable.
    missing_required = {
        name for name, field in model.model_fields.items() if field.is_required() and name not in signature.parameters
    }
    if missing_required:
        raise RuntimeError(
            f"{source_fn.__name__} cannot announce {model.__name__}: it does not declare the "
            f"REQUIRED field(s) {sorted(missing_required)}, so no call could ever construct a "
            f"valid request. Add the parameter(s) to the wrapper and forward them to the builder."
        )

    target.__signature__ = signature  # type: ignore[attr-defined]
    # __annotations__ too, and not merely for symmetry: FastMCP resolves parameter types
    # with typing.get_type_hints(), which reads __annotations__ and ignores __signature__.
    # Setting only the signature leaves the ADVERTISED types untouched while everything
    # looks correct under inspect.signature() -- the failure is silent in exactly the
    # place a reader would check.
    target.__annotations__ = {
        name: parameter.annotation
        for name, parameter in signature.parameters.items()
        if parameter.annotation is not inspect.Parameter.empty
    }
    return True
