"""Derive a tool's ADVERTISED parameter shape from the SDK request DTO.

The problem this removes
------------------------
An MCP tool's advertised ``inputSchema`` is generated by FastMCP from the Python
signature -- there is no separate declaration and no override hook. So the shape buyers
see has always been hand-written, and nothing tied it to the request DTO the SDK ships.
The two drifted freely: ``get_adcp_capabilities`` advertised ``protocols: list[str]``
where the DTO declares a typed enum, and ``ext: dict`` where the DTO declares
``ExtensionObject``. A buyer reading our schema and a buyer reading the spec saw
different contracts, and nothing failed.

The rule
--------
**Announced = the parameters the tool actually accepts; the DTO supplies the type of
every field it declares.** Both halves matter:

* A DTO field the tool does NOT accept is NOT announced. We never advertise a parameter
  the implementation would ignore, and there is no hand-maintained list of "unimplemented"
  fields to fall out of date -- absence from the signature IS the statement. To expose a
  new spec field you make the tool accept it, and the announcement follows automatically.
* A parameter the DTO DOES declare takes the DTO's type. This is the half that cannot
  drift: bump the SDK and every advertised type moves with it.

A third property was missing for a long time, and it is the one this module used to get
wrong: **the DTO supplies the TYPE, the library supplies the FIELD SET.** "Announced ==
accepted" said nothing about "announced == SPEC", and because the shape derives from OUR
subclass, a field added locally was published to buyers as though the spec defined it.
``list_accounts.idempotency_key`` was that field: account/list-accounts-request.json declares
no such property, the duty it was added for is TOLERANCE (that schema also declares
``additionalProperties: true``), and declaring it turned a tolerance obligation into an
invented spec field on MCP and REST. It has been removed.
``_refuse_fields_the_spec_does_not_define`` now refuses to register such a tool, so the state
is unreachable rather than recorded. A field we genuinely need is either ``exclude=True``
(internal, never announced) or listed in the DTO's ``_NON_SCHEMA_FIELDS`` with the reason it
is carried anyway.

A parameter the DTO does not declare is DROPPED from the announcement -- that is what
retires a legacy flat name such as ``list_creatives(status=...)``: FastMCP never passes what
it does not advertise, so there is no list of retired names to maintain. (This paragraph
used to say such a parameter "is still announced"; it never did, and a reader debugging why
a flat name stopped working was sent the wrong way by it.) Our advertised shape is therefore
always a SUBSET of the DTO, in exactly the DTO's form.

Transport independence
----------------------
This governs the ADVERTISED shape, which only MCP publishes. It deliberately does not
touch behaviour: A2A and REST reach the same ``_impl`` through the same request seam, so
the accepted field set and its meaning are identical everywhere and only the envelope
differs. Nothing here may become a per-transport branch.
"""

from __future__ import annotations

import inspect
import re
import sys
import typing
from collections.abc import Callable, Mapping
from typing import Annotated, Any

from pydantic import BaseModel
from pydantic import Field as PydanticField

from src.core.schema_helpers import accepted_kwargs, select_request_fields


def _is_injected(parameter: inspect.Parameter) -> bool:
    """True for a parameter FastMCP injects rather than one a buyer sends.

    Detected by ANNOTATION, not by a list of names. The only such parameter is the FastMCP
    ``Context``: it must stay in the signature so FastMCP can inject it, and FastMCP already
    keeps it out of the advertised schema. Everything else must be a DTO field or it is not
    a request parameter at all -- there is no denylist to maintain, because "is this buyer
    data?" is answered by the DTO, not by a name.
    """
    annotation = parameter.annotation
    if annotation is inspect.Parameter.empty:
        return False
    # Match the TYPE, not the spelling. A substring test on "Context" also matches the
    # spec's own ``ContextObject`` -- a real request field -- and would silently stop
    # advertising it.
    from fastmcp.server.context import Context as _FastMCPContext

    if any(arg is _FastMCPContext for arg in (annotation, *typing.get_args(annotation))):
        return True
    # Under `from __future__ import annotations` the annotation arrives as a STRING, so
    # get_args() returns () and the type test above sees nothing. Modules differ on this,
    # so the check must handle both: get_media_buys.ctx is 'Context | ToolContext | None'
    # while get_adcp_capabilities.ctx is the resolved class. Missing the string form drops
    # ctx from the derived signature, FastMCP then has nothing to inject, and every call
    # arrives without identity -- AUTH_MISSING on a properly authenticated request.
    if isinstance(annotation, str):
        return bool(re.search(r"\bContext\b", annotation))
    return False


#: Names a builder. The tool -> DTO edge is read from the ARTIFACT -- the builder the
#: wrapper actually references in its BYTECODE, and that builder's return annotation --
#: never from the tool's NAME. Name-joining would be fooled by the real cases:
#: ``_build_update_request`` returns ``UpdateMediaBuyRequest``. Reading ``co_names``
#: rather than source text also keeps this out of reach of the source-scanning ban
#: (a bytecode reference is the call itself, not a string that resembles one).
_BUILDER_NAME = re.compile(r"^(_?build_\w+_request|create_\w+_request)$")


def builder_for(fn: Callable[..., Any]) -> Callable[..., Any] | None:
    """The ONE builder a tool constructs its request through, or None when it has none.

    This is the tool -> builder edge, and every transport reads it rather than re-deriving
    "params to request" for itself. That is the whole point: a transport that looks the
    builder up cannot pick a different spelling, because there is nothing to pick.

    Resolved from the ARTIFACT -- the builder named in the wrapper's BYTECODE -- never from
    the tool's name. Name-joining would be fooled by the real cases: ``_build_update_request``
    returns ``UpdateMediaBuyRequest``.
    """
    builder_name = next((n for n in fn.__code__.co_names if _BUILDER_NAME.match(n)), None)
    if builder_name is None:
        return None

    module = sys.modules.get(fn.__module__)
    builder = getattr(module, builder_name, None)
    if builder is None:
        # Builders are often imported inside the function body; find the one module that
        # defines this name among those already imported.
        for loaded in list(sys.modules.values()):
            candidate = getattr(loaded, builder_name, None)
            if candidate is not None and getattr(candidate, "__name__", None) == builder_name:
                builder = candidate
                break
    return builder


def request_model_for(fn: Callable[..., Any]) -> type[BaseModel] | None:
    """The request DTO a tool builds, or None when it builds none.

    Derived from ``builder_for`` so the DTO and the builder can never disagree about which
    seam a tool uses -- they are the same lookup, read once.
    """
    builder = builder_for(fn)
    if builder is None:
        return None
    try:
        hints = typing.get_type_hints(builder)
    except Exception:
        return None
    model = hints.get("return")
    return model if isinstance(model, type) and issubclass(model, BaseModel) else None


def request_seam_for(fn: Callable[..., Any]) -> tuple[type[BaseModel], Callable[..., Any]]:
    """The ``(DTO, builder)`` pair ``fn`` constructs its request through. Refuses when it has none.

    This is the ONE lookup, and it exists so that a transport names the TOOL and nothing
    else. Before it, MCP derived the pair here while REST and A2A wrote both halves out by
    hand at every site -- ``derived_body_model("ListAccountsBody", ListAccountsRequest,
    build_list_accounts_request)`` and ``select_request_fields(ListAccountsRequest, params,
    accepted_kwargs(build_list_accounts_request))``. Two hand-written names per transport per
    tool is two places to name a DIFFERENT model or a DIFFERENT builder than the tool
    actually uses, and the disagreement is silent: the transport goes on accepting a field
    set nothing else accepts.

    Refusing rather than returning ``None``: a caller that cannot resolve the seam has no
    correct fallback -- selecting against "no DTO" forwards nothing and derives an empty body
    -- so the failure must arrive at the derivation, not as a tool that quietly accepts
    nothing. This mirrors ``_register_tool``, which refuses a tool whose DTO cannot be
    resolved instead of registering a hand-written shape.
    """
    builder = builder_for(fn)
    model = request_model_for(fn)
    if builder is None or model is None:
        raise RuntimeError(
            f"{getattr(fn, '__name__', fn)!r} has no request seam: a tool's DTO and builder "
            f"are read from the build_*_request it calls, and this one resolves "
            f"{'no builder' if builder is None else 'no DTO from its builder'}. Every "
            f"transport derives its accepted field set from that pair, so without it there "
            f"is nothing to derive from. Give the tool a build_*_request builder whose "
            f"return annotation is its request model."
        )
    return model, builder


def select_request_fields_for(fn: Callable[..., Any], source: BaseModel | Mapping[str, Any]) -> dict[str, Any]:
    """``select_request_fields`` with the DTO and the accepted set READ OFF THE TOOL.

    The selection RULE is unchanged -- it still lives in ``schema_helpers`` and is still
    "DTO fields INTERSECT the builder's parameters". What changes is that the caller no
    longer states which DTO and which builder that is: a skill handler names its tool, and
    the pair comes from the same lookup MCP registers with.
    """
    model, builder = request_seam_for(fn)
    return select_request_fields(model, source, accepted_kwargs(builder))


#: Contributed by version-envelope.json to every SDK request model. An ancestor that carries
#: only these grounds nothing -- it supplies no vocabulary for a DTO to be checked against.
_ENVELOPE_ONLY = frozenset({"adcp_version", "adcp_major_version"})


def sdk_grounding(model: type[BaseModel]) -> type[BaseModel] | None:
    """The SDK request model ``model`` inherits its vocabulary from, or None.

    "Announced = DTO fields INTERSECT the signature" only says something when the DTO comes
    from somewhere ELSE. A DTO hand-authored from the wrapper's own signature satisfies the
    intersection by construction: it declares what the wrapper declares, the derivation
    reproduces the hand-written shape, and the tool advertises whatever we happened to write
    while every test stays green. The DTO has to be the SPEC's vocabulary for the
    intersection to grade anything.

    Grounding is decided by walking the live MRO and asking where a field-carrying ancestor
    is DEFINED, so it consults no import spelling and has no spelling to miss.
    ``adcp.types.base.AdCPBaseModel`` and ``AdcpVersionEnvelope`` do not count: inheriting a
    base class with no request fields, or with the version envelope alone, leaves every
    buyer-facing field hand-written.
    """
    for ancestor in model.__mro__:
        module = ancestor.__module__
        if module != "adcp" and not module.startswith("adcp."):
            continue
        if set(getattr(ancestor, "model_fields", {})) - _ENVELOPE_ONLY:
            return ancestor
    return None


def _declared_description(annotation: Any) -> str | None:
    """The description already on the tool's own ``Annotated[...]``, if any.

    Taking the DTO's type must not silently erase buyer-facing text the tool wrote. A DTO
    field with no description of its own would otherwise blank the wrapper's -- five
    parameters lost their description that way before this existed, invisibly, because the
    advertised schema still validated.
    """
    if typing.get_origin(annotation) is not Annotated:
        return None
    for meta in typing.get_args(annotation)[1:]:
        description = getattr(meta, "description", None)
        if description:
            return str(description)
    return None


#: The ClassVar a DTO declares to name a field it carries that the spec does NOT define, and
#: to say why the field is nevertheless buyer-visible. Read off the class, never from a list
#: kept somewhere else: an entry sits at the definition site, next to the field it excuses,
#: and it cites the spec artifact that licenses it.
NON_SCHEMA_FIELDS_ATTR = "_NON_SCHEMA_FIELDS"


def library_declared_fields(model: type[BaseModel]) -> set[str]:
    """Every field name declared by an ``adcp`` class in ``model``'s ancestry (or by itself).

    This is "what the spec shape is", read from the SDK rather than from a schema file. The
    announcement already stakes everything on the DTO -- "bump the SDK and every advertised
    type moves with it" -- so the same artifact answers which fields the DTO's shape HAS.

    KNOWN LIMIT, and it is the SDK-vs-spec one. This project's rule is that the PINNED JSON
    SCHEMA is authoritative and the SDK is only a cross-check (CLAUDE.md), and this gate reads
    the SDK. Measured at adcp 6.6.0 the two agree for every registered tool -- the SDK types
    carry exactly the pinned schemas' field sets -- so the gate does not bite today. If the
    SDK ever LAGS the spec, the failure mode is that a field the spec genuinely defines gets
    refused and ``_NON_SCHEMA_FIELDS`` becomes the normal route for correct code, which is the
    opposite of what it is for. Watch for that shape of complaint rather than widening the rule.

    Not re-gated on the pinned tree because doing so means reading JSON files during
    ``import src.core.main`` (tools register at import), which makes the server's
    importability depend on the filesystem -- the thing
    ``test_architecture_no_import_time_fs_io`` exists to prevent -- and either couples ``src``
    to ``tests.helpers.pinned_schema`` or duplicates it. The schema direction is graded
    instead by ``TestNoNonSpecFieldsAreAdvertised``, which runs where file access is free.
    """
    return {
        name
        for base in model.__mro__
        if isinstance(base, type) and issubclass(base, BaseModel) and base.__module__.startswith("adcp.")
        for name in base.model_fields
    }


def non_schema_fields(model: type[BaseModel]) -> dict[str, str]:
    """The DTO's declared departures from the spec shape: field name -> spec citation.

    Unioned across the MRO so a subclass inherits its parent's citations instead of having to
    repeat them. An empty result is the normal case and the one that must stay normal.
    """
    citations: dict[str, str] = {}
    for base in reversed(model.__mro__):
        declared = base.__dict__.get(NON_SCHEMA_FIELDS_ATTR)
        if declared:
            citations.update(declared)
    return citations


def derived_signature(fn: Callable[..., Any], model: type[BaseModel]) -> inspect.Signature:
    """``fn``'s own parameters, retyped from ``model`` wherever it declares the field.

    The advertised type is the DTO's, always. Where this agent accepts MORE than the library
    (the brand shorthand), the widening is declared ON THE MODEL, so advertised == accepted
    without the derivation needing a narrowing rule. An earlier version guarded the narrow
    direction here instead; that put the exception in the wrong place and the model went on
    claiming a shape the tool did not implement.
    """
    signature = inspect.signature(fn)
    parameters = []
    for name, parameter in signature.parameters.items():
        if _is_injected(parameter):
            parameters.append(parameter)
            continue
        field = model.model_fields.get(name)
        if field is None:
            # Declared by the tool but NOT by the DTO -- a non-spec parameter. Dropped from
            # the advertised shape, which is what retires it: FastMCP never passes what it
            # does not advertise. No allowlist of legacy names to maintain; absence from
            # the DTO is the whole statement.
            continue
        if field.exclude:
            # INTERNAL. ``exclude=True`` is how this codebase says "never reaches a buyer",
            # and until now it said that about serialization ONLY -- the announcement read
            # right past it, so an internal field the wrapper happened to declare would have
            # been published as a request parameter. Honouring it here is what makes the
            # marker mean the same thing in both directions, and it is the escape the
            # non-spec refusal below leans on: a field we need locally is marked internal
            # rather than advertised as though the spec defined it.
            continue
        declared = parameter.annotation
        description = field.description or _declared_description(declared)
        # Typed Any because the two arms are genuinely different kinds: `field.annotation`
        # is a runtime type, while `Annotated[...]` is a typing special form. mypy inferred
        # the variable from the first assignment and then rejected the second; the value is
        # handed straight to Parameter.replace, which takes either.
        annotation: Any = field.annotation
        if description:
            annotation = Annotated[annotation, PydanticField(description=description)]
        parameters.append(parameter.replace(annotation=annotation, default=_advertised_default(parameter, field)))
    return signature.replace(parameters=parameters)


def _advertised_default(parameter: inspect.Parameter, field: Any) -> Any:
    """The default to ADVERTISE: the DTO's, wherever the DTO declares one.

    The same rule as the annotation two lines up, and for the same reason. FastMCP builds
    the published ``inputSchema`` from this signature, so whatever sits here is what a buyer
    reads as the field's default before they send anything -- and taking the TYPE from the
    DTO while leaving the DEFAULT as the wrapper happened to write it made the two halves of
    one field come from two places.

    They disagreed. Seven parameters advertised ``"default": null`` for fields their pinned
    schema declares with a real value (``sync_accounts.delete_missing`` / ``dry_run``,
    ``sync_creatives.validation_mode``, ``create_media_buy.paused``,
    ``get_media_buy_delivery.include_package_daily_breakdown`` /
    ``include_window_breakdown``, ``list_tasks.include_history``) -- so production behaved
    like the spec while the advertised contract said otherwise. Six MORE wrappers happened
    to restate the DTO's value correctly, which is the same defect in its harmless state:
    two declarations of one fact, one refactor away from disagreeing. Deriving here retires
    all thirteen, and the six restatements are deleted with it.

    A REQUIRED field has no default to take, and a wrapper cannot invent one: it keeps
    whatever it declared, which for a required DTO field is nothing (the missing-required
    refusal in ``apply_dto_announced_shape`` already forbids the alternative).

    A field whose DTO default is ``None`` also keeps the wrapper's, and that limit is
    deliberate rather than an oversight. ``None`` is the model declaring UNSET, not
    declaring a value -- there is nothing for the announcement to own, and the pinned
    schemas agree (``get-products-request.json`` gives ``brief`` no ``default`` at all).
    Deriving there would have REPLACED two live advertised defaults with null:
    ``get_products.brief`` (``""``) and ``complete_task.status`` (``"completed"``). Those
    two are a wrapper supplying a value its model does not describe, which is a real
    question and a different one; this rule cannot settle it, so it does not touch it.
    """
    if field.is_required():
        return parameter.default
    declared = field.default_factory() if field.default_factory is not None else field.default
    return parameter.default if declared is None else declared


def _refuse_fields_the_spec_does_not_define(
    source_fn: Callable[..., Any], model: type[BaseModel], signature: inspect.Signature
) -> None:
    """Refuse to announce a field our SUBCLASS invented on top of the library DTO.

    The announcement rule guarantees announced == accepted. It does NOT guarantee
    announced == SPEC, and until this refusal existed nothing did: because the advertised
    shape derives from OUR model, a field added to the subclass was published to buyers on
    MCP and REST as though the spec had defined it. ``ListAccountsRequest.idempotency_key``
    was that field, and it shows how the state is reached in practice -- not by carelessness
    but by a correct spec citation reasoned to the wrong conclusion. The duty
    ``read-tool-idempotency`` imposes is TOLERANCE, which list-accounts-request.json expresses
    as ``additionalProperties: true`` and the boundary already discharges; declaring a
    property to satisfy it advertised a field 3.1.1 does not define.

    A field is spec-declared when an ``adcp`` class in the DTO's ancestry declares it. When
    the ancestry declares NOTHING, the DTO is not extending a spec shape at all (it is a
    wholly local model, for a tool the spec does not define) and there is no shape for a
    field to be extra to -- so the rule is vacuous there rather than wrong.

    Two ways out, and both are declarations at the definition site rather than a list kept in
    a test:

    * ``exclude=True`` -- the field is INTERNAL. ``derived_signature`` already drops it, so
      it never reaches this check and never reaches a buyer.
    * ``_NON_SCHEMA_FIELDS`` -- the field is carried on purpose, and the entry says why.
      ``GetMediaBuysRequest.account_id`` is the one live case: a legacy filter predating the
      spec's ``account``, which live code still reads. Note what an entry is NOT: a place to
      park a field because removing it is work. Each one is a question someone has to answer,
      and answering ``idempotency_key``'s is what deleted it.

    Refusing rather than allowlisting, for the same reason the missing-required check below
    refuses: a list of known-bad tools records the violation, whereas refusing makes it
    unreachable -- the server cannot start.
    """
    library_declared = library_declared_fields(model)
    if not library_declared:
        return
    cited = non_schema_fields(model)
    declared_here = set(model.model_fields) - library_declared - set(cited)
    invented = sorted(set(signature.parameters) & declared_here)
    if not invented:
        return
    raise RuntimeError(
        f"{source_fn.__name__} cannot announce {model.__name__}: {invented} is declared by "
        f"{model.__name__} but by no adcp library type in its ancestry, so announcing it "
        f"would publish a field the spec does not define as though it did. Remove it, mark "
        f"it exclude=True if it is internal, or -- if a buyer genuinely must send it -- add "
        f"it to {model.__name__}.{NON_SCHEMA_FIELDS_ATTR} with the spec artifact that "
        f"licenses it."
    )


def apply_dto_announced_shape(target: Callable[..., Any], source_fn: Callable[..., Any]) -> bool:
    """Point ``target``'s advertised signature at the DTO. True when one was applied.

    ``target`` is what gets registered (the error-logging wrapper); ``source_fn`` is the
    undecorated tool, whose body names the builder.

    The model is resolved from the builder, full stop. The ``dto`` override this used to
    accept is gone with its last caller (list_tasks, rebased onto the SDK vocabulary): an
    unused override is one refactor away from being used again, and its whole effect was to
    let a tool advertise a shape no builder constructs.
    """
    model = request_model_for(source_fn)
    if model is None:
        return False
    signature = derived_signature(source_fn, model)
    _refuse_fields_the_spec_does_not_define(source_fn, model, signature)

    # A REQUIRED DTO field the wrapper does not declare can never be populated: the builder
    # never receives it, so every call raises ValidationError. That is a loud failure, but it
    # arrives at CALL time, on a buyer's request, for a defect fixed in one line at author
    # time. Measured across all 16 tools when this was added, no tool was in that state --
    # which is exactly when to nail it down, since the refusal costs nothing today and the
    # next tool cannot introduce it.
    #
    # Refusing rather than allowlisting, for the same reason _register_tool refuses an
    # unresolvable DTO: a list of known-broken tools records the violation, whereas refusing
    # makes the broken state unreachable.
    missing_required = {
        name for name, field in model.model_fields.items() if field.is_required() and name not in signature.parameters
    }
    if missing_required:
        raise RuntimeError(
            f"{source_fn.__name__} cannot announce {model.__name__}: it does not declare the "
            f"REQUIRED field(s) {sorted(missing_required)}, so no call could ever construct a "
            f"valid request. Add the parameter(s) to the wrapper and forward them to the builder."
        )

    target.__signature__ = signature  # type: ignore[attr-defined]
    # __annotations__ too, and not merely for symmetry: FastMCP resolves parameter types
    # with typing.get_type_hints(), which reads __annotations__ and ignores __signature__.
    # Setting only the signature leaves the ADVERTISED types untouched while everything
    # looks correct under inspect.signature() -- the failure is silent in exactly the
    # place a reader would check.
    target.__annotations__ = {
        name: parameter.annotation
        for name, parameter in signature.parameters.items()
        if parameter.annotation is not inspect.Parameter.empty
    }
    return True
